language: csharp
solution: PersonalSite.sln
sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
osx_image: xcode8.3
dotnet: 2.1.4
branches:
  only:
  - master