# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


variables:
  buildConfiguration: 'Release'

jobs: 
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: Build
  - script: dotnet test test/PersonalSite.Tests/PersonalSite.Tests.csproj --configuration $(buildConfiguration) --logger trx
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: Build
  - script: dotnet test test/PersonalSite.Tests/PersonalSite.Tests.csproj --configuration $(buildConfiguration) --logger trx
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: Build
  - script: dotnet test test/PersonalSite.Tests/PersonalSite.Tests.csproj --configuration $(buildConfiguration) --logger trx
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'