# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- template: azure-pipelines.build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'

- template: azure-pipelines.build.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-latest'

- template: azure-pipelines.build.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'windows-latest'
